on:
    repository_dispatch: 
        type: ["hello"]

jobs:
    some-action:
        runs-on: ubuntu-latest
        steps:
            - name: Print variables send from post
              run: echo ${{ github.event.client_payload.name }}
